FROM alpine:latest

RUN addgroup -g 1001 -S microuser && adduser -u 1001 -S microuser  -G microuser

ADD ./bin/socialnetwork /app/bin/
WORKDIR /app

ADD ./pkg/socialnetwork/data/tpl /socialnetwork/data/tpl

EXPOSE 8000

USER microuser
CMD ["./bin/socialnetwork"]