FROM alpine:latest

RUN addgroup -g 1001 -S microuser && adduser -u 1001 -S microuser  -G microuser

ADD ./bin/user /app/bin/
WORKDIR /app

ADD ./pkg/user/data/migrations /data/mysql/migrations
ENV MIGRATIONS_DIR=/data/mysql/migrations

EXPOSE 8000

USER microuser
CMD ["./bin/user"]