{
 "title": "User",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(app_request_count{job=\"user-metrics\"}[1m]))",
     "legendFormat": "RPS{{endpoint}}"
    },
    {}
   ]
  },
  {
   "title": "GRPC RPS App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (methodName) (rate(app_grpc_request_count{job=\"user-metrics\"}[1m]))",
     "legendFormat": "{{methodName}}"
    },
    {}
   ]
  },
  {
   "title": "Latency App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, endpoint) \n         (rate(app_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{endpoint}} 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, endpoint) \n         (rate(app_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{endpoint}} 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, endpoint) \n         (rate(app_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{endpoint}} 0.99"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le, endpoint) \n         (rate(app_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{endpoint}} max"
    },
    {}
   ]
  },
  {
   "title": "GRPC Latency App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, methodName) \n         (rate(app_grpc_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{methodName}} 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, methodName) \n         (rate(app_grpc_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{methodName}} 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, methodName) \n         (rate(app_grpc_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{methodName}} 0.99"
    },
    {
     "expr": "histogram_quantile(1, \n      sum by (le, methodName) \n         (rate(app_grpc_request_latency_seconds_bucket{job=\"user-metrics\"}[1m]))\n) * 1000",
     "legendFormat": "{{methodName}} max"
    },
    {}
   ]
  },
  {
   "title": "Error Rate App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (status, endpoint) (increase(app_server_error_count{job=\"user-metrics\", status=~\"5.+\"}[1m]))",
     "legendFormat": "{{status}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "GRPC Error Rate App",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (code, methodName) (increase(app_grpc_server_error_count{job=\"user-metrics\", status=~\"5.+\"}[1m]))",
     "legendFormat": "{{code}} {{methodName}}"
    },
    {}
   ]
  }
 ]
}